// GENERATED by scripts/build-help.mjs from src/help/*.md — edit the markdown, not this file.
export const GENERATED_HELP: { id: string; title: string; category: string; keywords: string; routes: string[]; body: string }[] = [
  {
    "id": "overview",
    "title": "How Whistle Ready works",
    "category": "Getting started",
    "keywords": "overview flow start basics workflow first steps",
    "routes": [],
    "body": "Whistle Ready runs a tournament end to end. The usual flow is:\n\n1. **Set up** the tournament (name, dates, fields, fee, divisions).\n2. Add **divisions**, sort teams into **pools**, and generate **brackets**.\n3. Use the **Scheduler** to place games on fields and times.\n4. Use the **Assigner** to put refs and scorekeepers on games.\n5. On event day, enter **scores** and use the **Game day** tools.\n6. Share the **Public page** (schedule, standings, brackets) and the **Event page** with teams.\n\nYou can jump to any step from the top navigation: **Setup**, **People**, **Game Day**, **Financials**, and **Settings**."
  },
  {
    "id": "setup",
    "title": "Set up a tournament",
    "category": "Setup",
    "keywords": "new tournament create setup wizard fields dates fee timing",
    "routes": [
      "/tournaments/*/builder"
    ],
    "body": "Create a tournament from the home page, then open **Setup** to fine‑tune it.\n\n- **General** — name, sport, dates, location, logo.\n- **Venues & Fields** — the complexes and fields games are played on, plus daily start/end times.\n- **Game timing & format** — period type (halves/quarters/running), length, and time between periods.\n- **Registration fees** and **Divisions** — see the related help articles.\n\nEverything you set here flows into the scheduler, the public page, and the registration form."
  },
  {
    "id": "divisions",
    "title": "Divisions, teams & pools",
    "category": "Setup",
    "keywords": "divisions teams pools assign auto-assign seed groups",
    "routes": [
      "/tournaments/*/divisions"
    ],
    "body": "Open **Setup → Divisions**. Each division has three tabs: **Teams & Pools**, **Games**, and **Bracket**.\n\n- Add teams to a division, then create **pools** (the chips at the top show live counts).\n- Toggle **Assign Pools** to drag teams between pool columns, or click **Auto‑assign teams** to fill pools evenly.\n- The **Games** tab lists pool games (P#) and bracket games (B#) with date/time/field.\n\nUse **Smart Defaults** to generate pools, pool games, and brackets in one click based on each team count."
  },
  {
    "id": "brackets",
    "title": "Brackets & flights",
    "category": "Setup",
    "keywords": "bracket playoff flight consolation seed advance champion",
    "routes": [
      "/tournaments/*/divisions"
    ],
    "body": "On a division's **Bracket** tab, pick a format and generate. The builder handles odd team counts with byes and real consolation games.\n\n- **Smart Defaults** sets games‑per‑team, bracket format, how many advance, and consolation.\n- A division can **split into Flight A / Flight B**, each with its own champion.\n- **Consolation (both‑ways)** renders a mirror: winners flow right to the Champion, first‑round losers drop left to a Consolation Champion.\n\nEdit any matchup inline, and preview before you publish."
  },
  {
    "id": "scheduler",
    "title": "Scheduling games (Auto‑fill)",
    "category": "Setup",
    "keywords": "scheduler schedule auto-fill grid times fields day split conflicts",
    "routes": [
      "/tournaments/*/scheduler"
    ],
    "body": "Open **Setup → Scheduler**. The grid shows fields across the top and time slots down the side.\n\n- **Day start / Day end** load from your saved daily times and persist.\n- Drag a game from the parking lot onto a slot, or click **Auto‑fill** to place them by the rules (no team/field double‑book, brackets after their feeders, rest between games, spread across fields).\n- The **Day‑split** dropdown chooses how days are used (pool day 1 / bracket day 2, pool across all days, or all on one day).\n- Use the **Game‑type** filter to schedule pool vs bracket separately, and **Zoom** to see more at once.\n\nRefs and scorekeepers are added later on the Assigner."
  },
  {
    "id": "registration",
    "title": "Team registration & fees",
    "category": "Registration & money",
    "keywords": "registration register fee tier pricing 7v7 public form divisions",
    "routes": [
      "/tournaments/*/registrations",
      "/tournaments/*/builder"
    ],
    "body": "Teams sign up on your public **Register** page. You control it under **Settings → Registration Fees** and **Divisions**.\n\n- Fees use **per‑team tiers**. Add or remove tiers with **+ Add tier** and the × button; ranges chain automatically (1–3, 4–6, 7+ …) and the last tier is \"and up\".\n- Add an optional **flat‑rate tier** (e.g. 7v7) with its own name and the divisions it applies to.\n- The register form shows your divisions and a live fee estimate as teams are added.\n\nChange anything and press **Save Changes** — the public form updates immediately."
  },
  {
    "id": "registration-emails",
    "title": "Who gets new-registration emails",
    "category": "Registration & money",
    "keywords": "notify notification notifications email alert heads-up new registration who gets emails recipients organizer office co-director",
    "routes": [
      "/dashboard/org/forms",
      "/tournaments/*/builder"
    ],
    "body": "Every new team registration sends your team an internal heads-up (contact info, teams, payment status) so someone can call the club director.\n\n**For all your events (org default):**\n1. From the home dashboard, open **Forms**.\n2. Open **Registration Confirmation**.\n3. Under **Notify your team**, enter the addresses, comma-separated. Leave it blank to use your org contact email.\n4. To notify someone for certain events only (for example a co-director), click **Add person** under **Notify specific people by event** and tick their events. New yearly editions are included automatically.\n\n**For one tournament:**\n1. Open **Setup → Tournament setup → Team fees**.\n2. Scroll to **Confirmation letter** and fill in **Notify your team**. Leave it blank to use the org default.\n\nNote: the **Notify me at** fields on the Forms page belong to the vendor and staff application forms, not team registration."
  },
  {
    "id": "financials",
    "title": "Financials & payments",
    "category": "Registration & money",
    "keywords": "money financials payments invoice collected balance stripe check",
    "routes": [
      "/tournaments/*/financials"
    ],
    "body": "**Financials** shows what's invoiced, collected, and outstanding across team and player registrations.\n\n- Registrants can pay by card (Stripe) or manual methods (Check, Zelle, ACH, PayPal) depending on what you enable.\n- The **Registrations** page lists each club, its teams, invoice amount, and payments.\n- Record manual payments against a registration to keep the balance accurate."
  },
  {
    "id": "roster",
    "title": "Staff roster & availability",
    "category": "Staff",
    "keywords": "staff roster availability pay rates refs scorekeepers workers",
    "routes": [
      "/tournaments/*/roster"
    ],
    "body": "Build your working staff under **People → Staff roster**.\n\n- Add staff to the tournament roster (refs, scorekeepers, field ops, trainers).\n- **Availability** lets staff mark which days/times they can work.\n- **Pay rates** and **Pay summary** track what each role earns and totals owed.\n\nOn‑field workers all log in as **Staff**; their specific job comes from their Assigner assignments."
  },
  {
    "id": "assigner",
    "title": "Assigning refs & scorekeepers",
    "category": "Staff",
    "keywords": "assigner assign refs scorekeepers staffing slots lock",
    "routes": [
      "/tournaments/*"
    ],
    "body": "Open **Setup → Assigner** after games are scheduled.\n\n- Drag staff from the pool onto a game's role slots.\n- Set how many refs each game needs, and see staffing requirements at a glance.\n- Use the **lock‑editing** toggle to prevent accidental changes once you're set.\n\nAssignments determine who can open the live scorekeeper for a game."
  },
  {
    "id": "scores",
    "title": "Scores & live scorekeeping",
    "category": "Game day",
    "keywords": "scores scorekeeper live game results enter standings",
    "routes": [
      "/tournaments/*/scores"
    ],
    "body": "Track results from the **Scores** page (directors/assigners). It shows scored vs total games.\n\n- Open a game's **Scorekeeper** view to run the clock and enter the score live.\n- Scores flow straight into **standings** on the public page (with your configured tiebreakers).\n\nOnly staff assigned to a game (or with the scorekeeper permission) can open its live scorekeeper."
  },
  {
    "id": "gameday",
    "title": "Game day tools",
    "category": "Game day",
    "keywords": "game day ops board incidents checklist directory contacts messages",
    "routes": [
      "/tournaments/*/communications",
      "/tournaments/*/ops",
      "/tournaments/*/incidents",
      "/tournaments/*/checklist",
      "/tournaments/*/directory"
    ],
    "body": "On event day, the **Game Day** menu has mobile‑friendly tools for everyone working:\n\n- **Ops board** — send quick messages (\"ball to Field 5\", \"trainer to Field 7\") to a group or everyone.\n- **Incidents** — log medical/safety/facility/weather issues with severity and field; track open vs resolved.\n- **Setup checklist** — a shared list anyone can check off and add to.\n- **Staff directory** — searchable, tap to call or text."
  },
  {
    "id": "public",
    "title": "Public page & event page",
    "category": "Public pages",
    "keywords": "public page event page schedule standings bracket builder blocks tabs",
    "routes": [
      "/tournaments/*/builder"
    ],
    "body": "Two public‑facing pages share your tournament with teams and families.\n\n- The **Public page** has division standings, a grouped schedule (filters, add‑to‑calendar), and full bracket trees.\n- The **Event page** is a builder‑driven landing page: drag blocks (overview, fees, locations, hotels, rules, FAQ, countdown, schedule, standings) and arrange them, with an **Event info** menu and a tabbed layout.\n\nEdit the event page under **Setup → Event page → Page builder**. Use **Generate with AI** to draft section copy."
  }
]
