// Builds Chirp's manual from src/help/*.md into src/lib/helpArticles.generated.ts.
// Runs automatically before every `npm run build` (the "prebuild" script), so
// Vercel always ships what the markdown says. Run it by hand after editing a
// help page if you want local dev to pick it up:   node scripts/build-help.mjs
//
// A help page is one markdown file per topic with front matter:
//   ---
//   title: Who gets new-registration emails
//   category: Registration & money
//   order: 70                      (sort within the manual; lower first)
//   routes: /dashboard/org/forms, /tournaments/*/builder
//   keywords: notify email alert recipients
//   audience: staff                (staff = signed-in staff Chirps, the default;
//                                    public = coaches, parents and visitors;
//                                    both = either)
//   ---
// `routes` are the pages the topic is about ('*' = tournament id). A role sees
// the page when it can open at least one of them; no routes = everyone.
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const dir = path.join(root, 'src/help')
const out = path.join(root, 'src/lib/helpArticles.generated.ts')

const articles = []
for (const file of fs.readdirSync(dir).filter(f => f.endsWith('.md')).sort()) {
  const raw = fs.readFileSync(path.join(dir, file), 'utf8').replace(/\r\n/g, '\n')
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/)
  if (!m) throw new Error(`${file}: missing front matter`)
  const meta = {}
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^(\w+):\s*(.*)$/)
    if (kv) meta[kv[1]] = kv[2].trim()
  }
  if (!meta.title || !meta.category) throw new Error(`${file}: title and category are required`)
  articles.push({
    id: file.replace(/\.md$/, ''),
    title: meta.title,
    category: meta.category,
    order: Number(meta.order) || 999,
    keywords: meta.keywords || '',
    routes: (meta.routes || '').split(',').map(s => s.trim()).filter(Boolean),
    audience: ['public', 'both'].includes(meta.audience) ? meta.audience : 'staff',
    body: m[2].trim(),
  })
}
articles.sort((a, b) => a.order - b.order || a.title.localeCompare(b.title))

const ts = `// GENERATED by scripts/build-help.mjs from src/help/*.md — edit the markdown, not this file.
export const GENERATED_HELP: { id: string; title: string; category: string; keywords: string; routes: string[]; audience: 'staff' | 'public' | 'both'; body: string }[] = ${JSON.stringify(articles.map(({ order, ...a }) => a), null, 2)}
`
fs.writeFileSync(out, ts)
console.log(`help: ${articles.length} pages -> ${path.relative(root, out)}`)
